esphome:
  name: esp32cams
  platform: ESP32
  board: esp32cam

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: control_servo_pan
      variables:
        level: float
      then:
        - servo.write:
            id: servo_pan
            level: !lambda 'return level / 100.0;'
    - service: control_servo_tilt
      variables:
        level: float
      then:
        - servo.write:
            id: servo_tilt
            level: !lambda 'return level / 100.0;'


ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Cams Fallback Hotspot"
    password: !secret ap_password

captive_portal:


servo:
  - id: servo_pan
    output: servo_pan_output
    transition_length: 4s
    auto_detach_time: 2s
  - id: servo_tilt
    output: servo_tilt_output
    transition_length: 4s
    auto_detach_time: 2s

# ESP32-CAM
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: XGA
  name: mycamera
  vertical_flip: false
  horizontal_mirror: false

output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
  - platform: ledc
    id: servo_pan_output
    pin: GPIO12
    frequency: 50 Hz
    channel: 2
  - platform: ledc
    id: servo_tilt_output
    pin: GPIO13
    frequency: 50 Hz
    channel: 3

## GPIO_4 is the flash light pin
light:
  - platform: binary
    output: gpio_4
    name: esp32camslight

